package sn.ucad.fst.dmi.mtdsi.recherche.modelDAO;
// Generated 8 juil. 2024, 01:00:08 by Hibernate Tools 5.6.15.Final

/**
 * Adherent generated by hbm2java
 */
public class Adherent implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idAdherent;
	private int idPret;
	private String emailetudiant;
	private String numerocarteetudiant;

	public Adherent() {
	}

	public Adherent(int idPret, String emailetudiant, String numerocarteetudiant) {
		this.idPret = idPret;
		this.emailetudiant = emailetudiant;
		this.numerocarteetudiant = numerocarteetudiant;
	}

	public Integer getIdAdherent() {
		return this.idAdherent;
	}

	public void setIdAdherent(Integer idAdherent) {
		this.idAdherent = idAdherent;
	}

	public int getIdPret() {
		return this.idPret;
	}

	public void setIdPret(int idPret) {
		this.idPret = idPret;
	}

	public String getEmailetudiant() {
		return this.emailetudiant;
	}

	public void setEmailetudiant(String emailetudiant) {
		this.emailetudiant = emailetudiant;
	}

	public String getNumerocarteetudiant() {
		return this.numerocarteetudiant;
	}

	public void setNumerocarteetudiant(String numerocarteetudiant) {
		this.numerocarteetudiant = numerocarteetudiant;
	}

}
