package sn.ucad.fst.dmi.mtdsi.recherche.modelDAO;
// Generated 8 juil. 2024, 01:00:08 by Hibernate Tools 5.6.15.Final

/**
 * Bibliothecaire generated by hbm2java
 */
public class Bibliothecaire implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idBibliothecaire;
	private String nom;
	private String prenom;
	private String email;
	private String telephone;

	public Bibliothecaire() {
	}

	public Bibliothecaire(String nom, String prenom, String email, String telephone) {
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.telephone = telephone;
	}

	public Integer getIdBibliothecaire() {
		return this.idBibliothecaire;
	}

	public void setIdBibliothecaire(Integer idBibliothecaire) {
		this.idBibliothecaire = idBibliothecaire;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

}
