package sn.ucad.fst.dmi.mtdsi.recherche.modelDAO;
// Generated 8 juil. 2024, 01:00:08 by Hibernate Tools 5.6.15.Final

/**
 * Bibliotheque generated by hbm2java
 */
public class Bibliotheque implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idBibliotheque;
	private int idPret;
	private int idBibliothecaire;
	private int idDocument;
	private String nombu;
	private String emailbu;

	public Bibliotheque() {
	}

	public Bibliotheque(int idPret, int idBibliothecaire, int idDocument) {
		this.idPret = idPret;
		this.idBibliothecaire = idBibliothecaire;
		this.idDocument = idDocument;
	}

	public Bibliotheque(int idPret, int idBibliothecaire, int idDocument, String nombu, String emailbu) {
		this.idPret = idPret;
		this.idBibliothecaire = idBibliothecaire;
		this.idDocument = idDocument;
		this.nombu = nombu;
		this.emailbu = emailbu;
	}

	public Integer getIdBibliotheque() {
		return this.idBibliotheque;
	}

	public void setIdBibliotheque(Integer idBibliotheque) {
		this.idBibliotheque = idBibliotheque;
	}

	public int getIdPret() {
		return this.idPret;
	}

	public void setIdPret(int idPret) {
		this.idPret = idPret;
	}

	public int getIdBibliothecaire() {
		return this.idBibliothecaire;
	}

	public void setIdBibliothecaire(int idBibliothecaire) {
		this.idBibliothecaire = idBibliothecaire;
	}

	public int getIdDocument() {
		return this.idDocument;
	}

	public void setIdDocument(int idDocument) {
		this.idDocument = idDocument;
	}

	public String getNombu() {
		return this.nombu;
	}

	public void setNombu(String nombu) {
		this.nombu = nombu;
	}

	public String getEmailbu() {
		return this.emailbu;
	}

	public void setEmailbu(String emailbu) {
		this.emailbu = emailbu;
	}

}
