package sn.ucad.fst.dmi.mtdsi.recherche.modelDAO;
// Generated 8 juil. 2024, 01:00:08 by Hibernate Tools 5.6.15.Final

import java.math.BigInteger;
import java.util.Date;

/**
 * Emprunt generated by hbm2java
 */
public class Emprunt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idPret;
	private Integer idBibliothecaire;
	private Integer idDocument;
	private Date datedebutpret;
	private Date datefinpret;
	private Integer dureeemprunt;
	private BigInteger penalites;

	public Emprunt() {
	}

	public Emprunt(Integer idBibliothecaire, Integer idDocument, Date datedebutpret, Date datefinpret,
			Integer dureeemprunt, BigInteger penalites) {
		this.idBibliothecaire = idBibliothecaire;
		this.idDocument = idDocument;
		this.datedebutpret = datedebutpret;
		this.datefinpret = datefinpret;
		this.dureeemprunt = dureeemprunt;
		this.penalites = penalites;
	}

	public Integer getIdPret() {
		return this.idPret;
	}

	public void setIdPret(Integer idPret) {
		this.idPret = idPret;
	}

	public Integer getIdBibliothecaire() {
		return this.idBibliothecaire;
	}

	public void setIdBibliothecaire(Integer idBibliothecaire) {
		this.idBibliothecaire = idBibliothecaire;
	}

	public Integer getIdDocument() {
		return this.idDocument;
	}

	public void setIdDocument(Integer idDocument) {
		this.idDocument = idDocument;
	}

	public Date getDatedebutpret() {
		return this.datedebutpret;
	}

	public void setDatedebutpret(Date datedebutpret) {
		this.datedebutpret = datedebutpret;
	}

	public Date getDatefinpret() {
		return this.datefinpret;
	}

	public void setDatefinpret(Date datefinpret) {
		this.datefinpret = datefinpret;
	}

	public Integer getDureeemprunt() {
		return this.dureeemprunt;
	}

	public void setDureeemprunt(Integer dureeemprunt) {
		this.dureeemprunt = dureeemprunt;
	}

	public BigInteger getPenalites() {
		return this.penalites;
	}

	public void setPenalites(BigInteger penalites) {
		this.penalites = penalites;
	}

}
