package sn.ucad.fst.dmi.mtdsi.recherche.modelDAO;
// Generated 8 juil. 2024, 01:00:08 by Hibernate Tools 5.6.15.Final

/**
 * Revue generated by hbm2java
 */
public class Revue implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idDocument;
	private String typeDocument;
	private Integer numenreg;
	private String titre;
	private Integer mois;
	private Integer annee;

	public Revue() {
	}

	public Revue(String typeDocument) {
		this.typeDocument = typeDocument;
	}

	public Revue(String typeDocument, Integer numenreg, String titre, Integer mois, Integer annee) {
		this.typeDocument = typeDocument;
		this.numenreg = numenreg;
		this.titre = titre;
		this.mois = mois;
		this.annee = annee;
	}

	public Integer getIdDocument() {
		return this.idDocument;
	}

	public void setIdDocument(Integer idDocument) {
		this.idDocument = idDocument;
	}

	public String getTypeDocument() {
		return this.typeDocument;
	}

	public void setTypeDocument(String typeDocument) {
		this.typeDocument = typeDocument;
	}

	public Integer getNumenreg() {
		return this.numenreg;
	}

	public void setNumenreg(Integer numenreg) {
		this.numenreg = numenreg;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public Integer getMois() {
		return this.mois;
	}

	public void setMois(Integer mois) {
		this.mois = mois;
	}

	public Integer getAnnee() {
		return this.annee;
	}

	public void setAnnee(Integer annee) {
		this.annee = annee;
	}

}
